from __future__ import annotations

from datetime import datetime, timedelta
from decimal import Decimal

PRODUCTS = [
    {
        "id": 1,
        "nome": "Camiseta Neural Black",
        "descricao": "Camiseta premium em algodão penteado, com estampa minimalista inspirada em inteligência artificial.",
        "preco": Decimal("119.90"),
        "categoria": "Camisetas",
        "imagem": "assets/products/camiseta-neural.svg",
        "estoque": 32,
        "destaque": True,
        "data_criacao": datetime.utcnow() - timedelta(days=18),
    },
    {
        "id": 2,
        "nome": "Moletom Quantum Purple",
        "descricao": "Moletom oversized com acabamento macio, capuz estruturado e visual urbano tecnológico.",
        "preco": Decimal("249.90"),
        "categoria": "Moletons",
        "imagem": "assets/products/moletom-quantum.svg",
        "estoque": 14,
        "destaque": True,
        "data_criacao": datetime.utcnow() - timedelta(days=12),
    },
    {
        "id": 3,
        "nome": "Boné Signature IA",
        "descricao": "Boné ajustável com bordado discreto da marca IA Colecction e design premium.",
        "preco": Decimal("89.90"),
        "categoria": "Acessórios",
        "imagem": "assets/products/bone-signature.svg",
        "estoque": 40,
        "destaque": False,
        "data_criacao": datetime.utcnow() - timedelta(days=26),
    },
    {
        "id": 4,
        "nome": "Tênis Future Step",
        "descricao": "Tênis casual com linhas futuristas, confortável para rotina urbana e combinações modernas.",
        "preco": Decimal("329.90"),
        "categoria": "Calçados",
        "imagem": "assets/products/tenis-future.svg",
        "estoque": 9,
        "destaque": True,
        "data_criacao": datetime.utcnow() - timedelta(days=5),
    },
    {
        "id": 5,
        "nome": "Camiseta Code White",
        "descricao": "Peça leve com visual clean, ideal para looks casuais com identidade tecnológica.",
        "preco": Decimal("99.90"),
        "categoria": "Promoções",
        "imagem": "assets/products/camiseta-code.svg",
        "estoque": 21,
        "destaque": True,
        "data_criacao": datetime.utcnow() - timedelta(days=35),
    },
    {
        "id": 6,
        "nome": "Shoulder Bag Tech",
        "descricao": "Bolsa transversal compacta com divisórias internas e acabamento resistente para uso diário.",
        "preco": Decimal("139.90"),
        "categoria": "Acessórios",
        "imagem": "assets/products/shoulder-tech.svg",
        "estoque": 18,
        "destaque": False,
        "data_criacao": datetime.utcnow() - timedelta(days=9),
    },
    {
        "id": 7,
        "nome": "Moletom Minimal Grey",
        "descricao": "Moletom cinza com modelagem confortável, visual elegante e etiqueta premium da coleção.",
        "preco": Decimal("219.90"),
        "categoria": "Moletons",
        "imagem": "assets/products/moletom-grey.svg",
        "estoque": 16,
        "destaque": False,
        "data_criacao": datetime.utcnow() - timedelta(days=20),
    },
    {
        "id": 8,
        "nome": "Jaqueta Launch Edition",
        "descricao": "Jaqueta leve de lançamento com detalhes modernos, bolsos funcionais e presença premium.",
        "preco": Decimal("389.90"),
        "categoria": "Lançamentos",
        "imagem": "assets/products/jaqueta-launch.svg",
        "estoque": 7,
        "destaque": True,
        "data_criacao": datetime.utcnow() - timedelta(days=2),
    },
]
