from __future__ import annotations

from datetime import datetime, timedelta
from decimal import Decimal

PRODUCTS = [
    {
        "id": 1,
        "nome": "Vestido Aurora Vinho",
        "descricao": "Vestido feminino midi em tom vinho, com caimento elegante, toque macio e acabamento sofisticado para ocasiões especiais.",
        "preco": Decimal("189.90"),
        "categoria": "Vestidos",
        "imagem": "assets/products/vestido-aurora.svg",
        "estoque": 18,
        "destaque": True,
        "data_criacao": datetime.utcnow() - timedelta(days=18),
    },
    {
        "id": 2,
        "nome": "Blusa Marfim Elegance",
        "descricao": "Blusa feminina em tecido leve na cor marfim, com modelagem delicada e versátil para composições casuais ou refinadas.",
        "preco": Decimal("99.90"),
        "categoria": "Blusas",
        "imagem": "assets/products/blusa-marfim.svg",
        "estoque": 26,
        "destaque": True,
        "data_criacao": datetime.utcnow() - timedelta(days=12),
    },
    {
        "id": 3,
        "nome": "Conjunto Lívia Premium",
        "descricao": "Conjunto feminino sofisticado com blusa e saia em tons neutros, pensado para looks modernos, confortáveis e elegantes.",
        "preco": Decimal("259.90"),
        "categoria": "Conjuntos",
        "imagem": "assets/products/conjunto-livia.svg",
        "estoque": 12,
        "destaque": True,
        "data_criacao": datetime.utcnow() - timedelta(days=10),
    },
    {
        "id": 4,
        "nome": "Saia Midi Bella",
        "descricao": "Saia midi com cintura alta, movimento leve e acabamento premium. Uma peça versátil para produções femininas elegantes.",
        "preco": Decimal("139.90"),
        "categoria": "Saias",
        "imagem": "assets/products/saia-bella.svg",
        "estoque": 20,
        "destaque": False,
        "data_criacao": datetime.utcnow() - timedelta(days=8),
    },
    {
        "id": 5,
        "nome": "Sandália Valentina Gold",
        "descricao": "Sandália feminina com detalhe dourado suave, design delicado e confortável para completar looks casuais ou sociais.",
        "preco": Decimal("179.90"),
        "categoria": "Calçados",
        "imagem": "assets/products/sandalia-valentina.svg",
        "estoque": 10,
        "destaque": True,
        "data_criacao": datetime.utcnow() - timedelta(days=5),
    },
    {
        "id": 6,
        "nome": "Bolsa Grace Vinho",
        "descricao": "Bolsa feminina compacta em tom vinho, com alça elegante, espaço interno funcional e acabamento sofisticado.",
        "preco": Decimal("159.90"),
        "categoria": "Acessórios",
        "imagem": "assets/products/bolsa-grace.svg",
        "estoque": 16,
        "destaque": False,
        "data_criacao": datetime.utcnow() - timedelta(days=4),
    },
    {
        "id": 7,
        "nome": "Vestido Flora Lançamento",
        "descricao": "Vestido lançamento com visual delicado, detalhes femininos e proposta elegante para mulheres que valorizam presença e estilo.",
        "preco": Decimal("219.90"),
        "categoria": "Lançamentos",
        "imagem": "assets/products/vestido-flora.svg",
        "estoque": 8,
        "destaque": True,
        "data_criacao": datetime.utcnow() - timedelta(days=2),
    },
    {
        "id": 8,
        "nome": "Cinto Laço Sofisticado",
        "descricao": "Acessório feminino em promoção, com detalhe em laço e acabamento delicado para valorizar vestidos, saias e conjuntos.",
        "preco": Decimal("69.90"),
        "categoria": "Promoções",
        "imagem": "assets/products/cinto-laco.svg",
        "estoque": 30,
        "destaque": False,
        "data_criacao": datetime.utcnow() - timedelta(days=1),
    },
]
